##Tensorflow

In [1]:
pip install tensorflow

In [2]:
%tensorflow_version 2.x  # this line is not required unless you are in a notebook

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x  # this line is not required unless you are in a notebook`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.


In [3]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [4]:
#creating tensors

string = tf.Variable("this is a string", tf.string) #string types of sensors are rare
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

#all of these are tesnors of rank 0, i.e. SCALAR tensors

##Rank of tensors

In [16]:
rank1_tensor=tf.Variable(["Tim", "Test", "OK"], tf.string)
rank2_tensor=tf.Variable([["test", "ok","klkd"], ["test", "yes", "lfkl"], ["new", "old", "sdkfkd"]], tf.string)  #it has to be a uniform amount of elements

In [14]:
#determining the rank of tensor rank2_tensor; we can se that that is 2 (numpy=2)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [10]:
#determining the rank of tensor rank1_tensor; we can se that that is 1 (numpy=1)
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [11]:
#determining the rank of tensor 'number'; we can se that that is 0 (numpy=0)
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

##Shape of tensors

SHAPE = num of arrays X num of elements

In [17]:
rank2_tensor.shape

TensorShape([3, 3])

##Changing shape

IMPORTANT: The numer of elements in the reshaped tensor MUST match the number in the original

In [18]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [19]:
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [21]:
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,3]
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


##Slicing tensors

The slice operator can be used on tensors to select specific axes or elements. When we slice or select elements from a tensor, we can use comma seperated values inside the set of square brackets. Each subsequent value refrences a different dimension of the tensor.

Ex: tensor[dim1, dim2, dim3] 

In [25]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)
print(matrix)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]


In [28]:
three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3



tf.Tensor(3, shape=(), dtype=int32)


In [29]:
row1 = tensor[0]  # selects the first row
print(row1)


tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [30]:
column1 = tensor[:, 0]  # selects the first column
print(column1)


tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)


In [31]:
row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)


tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)


In [32]:
column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor([ 6 11], shape=(2,), dtype=int32)


When slicing, [1:3] means slice index 1 to index 3 not including index 3
              [2,0] represents row, column
              [1:3, 0] respresents row 1-3, column
              [1, 1-4] represents row 1, column 1-4

###Types of Tensors
Before we go to far, I will mention that there are diffent types of tensors. These are the most used and we will talk more in depth about each as they are used.
- Variable
- Constant
- Placeholder
- SparseTensor

With the execption of ```Variable``` all these tensors are immuttable, meaning their value may not change during execution.

For now, it is enough to understand that we use the Variable tensor when we want to potentially change the value of our tensor.


###Evaluating tensors

-to evaluate=> get its value.

Since tensors represent a partially complete computation we will sometimes need to run a "session" to evaluate a tensor


with tf.compat.v1.Session() as sess: tensor.eval()